version: '3.8'

services:

  fridge-db:
    image: postgres:14.0-alpine
    volumes:
      - ./FridgeDB/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - firdge_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  firdge_data:
